### ISSUE TITLE
What should I do if I want to input a longer sentence

### ISSUE THREAD

**Issue by KawhiZhao** [yuantiku/PoDA#2]
There is always the issue "Exception: Size of sample #9 is invalid, max_positions=(100000, 100000), skip this example with --skip-invalid-size-inputs-valid-test" and I do not want to skip any examples

**Comment by intfloat** [comment]
You can increase the maximum number of tokens in source input with `--max-source-positions`, and target input with `--max-target-positions`. 

The default value in https://github.com/yuantiku/PoDA/blob/master/giga/finetune.sh#L52 is 500, which is already pretty large and should be sufficient for most cases, longer inputs will make the training significantly slower.

**Comment by KawhiZhao** [comment]
Thanks for reponse!
What if I want to input a longer sentence in inference stage instead of finetune stage (or run the generate.sh)
There is always the same problem "Exception: Size of sample #9 is invalid, max_positions=(100000, 100000), skip this example with --skip-invalid-size-inputs-valid-test"

**Comment by intfloat** [comment]
The maximum length is specified during train/finetune stage. If your model is trained to accept at most `500` input tokens, then at inference stage it will only accept sentences with no more than `500` tokens. Currently it doesn't support dynamically change `--max-source-positions` at inference stage.

**Comment by KawhiZhao** [comment]
Thanks!
