### ISSUE TITLE
Where is Pointer-Generator Layer part?

### ISSUE THREAD

**Issue by HyejinWon** [yuantiku/PoDA#3]
Can not find Pointer-Generator Layer in your train.sh code.

**Comment by intfloat** [comment]
The pointer-generator layer corresponds to `--use-copy True` in train.sh (https://github.com/yuantiku/PoDA/blob/master/giga/train.sh#L51)

For implementation details, please check out changes for `fairseq/fairseq/models/fairseq_decoder.py` and `fairseq/fairseq/models/transformer.py` in commit cf7ca94aebbce1901ee90045cb023cce9a6e4412

**Comment by HyejinWon** [comment]
How can I train your model? Used my own dataset.
(Not used your pre-train model)
